events {}

http {
    # Brute-force protection
    limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;

    # Редирект с HTTP на HTTPS
    server {
        listen 80;
    
        location / {
            proxy_pass http://frontend:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/auth/login {
            limit_req zone=login burst=5 nodelay;
            proxy_pass http://backend:8000/auth/login;
        }
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        # Frontend
        location / {
          proxy_pass http://frontend:5173;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade"; # нужно для Vite HMR
          proxy_set_header Host $host;
        }

        # Backend API
        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Rate limiting для логина
        location /api/auth/login {
            limit_req zone=login burst=5 nodelay;
            proxy_pass http://backend:8000/auth/login;
        }
    }
}